/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.managament.system;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abh
 */
public class Transaction1 extends javax.swing.JFrame {

    /**
     * Creates new form Transaction1
     */
    public Transaction1() {
        initComponents();
    }
    public void Table2() {
        Connection con;
        ResultSet rs = null;
        PreparedStatement ps = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "Vikram@123");
            String query = "select fname,lname,deposite,withdraw,AccountNo from transaction where AccountNo=?";
            ps=con.prepareStatement(query);
           ps.setString(1,jTextField2.getText());
           rs=ps.executeQuery();
           // ps = con.prepareStatement(query);
          //  rs = ps.executeQuery();
         //   jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         ResultSetMetaData rsmt = (ResultSetMetaData) rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int cols = rsmt.getColumnCount();
            String[] colName = new String[cols];
            for (int i = 0; i < cols; i++) {
                colName[i] = rsmt.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(colName);
            String fname,lname,deposite,withdraw,AccountNo;
            model.setColumnIdentifiers(colName);
            while (rs.next()) {
                fname = rs.getString(1);
                lname = rs.getString(2);
                deposite = rs.getString(3);
                withdraw = rs.getString(4);
                AccountNo = rs.getString(5);
                String[] row = {fname,lname,deposite,withdraw,AccountNo};
                model.addRow(row);
            }
            ps.close();
            con.close();

        } catch (Exception e) {
            e.printStackTrace();

        }
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Table2();
//        ArrayList array = new ArrayList();
//        try {
//            String acctNo = jTextField2.getText();
//
//            if (acctNo.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Please Enter Bank Account Number to Search!", "Banking System - Required Information.", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                try {
//                    Class.forName("com.mysql.cj.jdbc.Driver");
//                    String db = "jdbc:mysql://localhost:3306/bank";
//                    String username = "root";
//                    String password = "Vikram@123";
//
//                    try ( Connection con = DriverManager.getConnection(db, username, password)) {
//                        Statement statement = con.createStatement();
//                        String sql = "SELECT * FROM registration WHERE accountno='" + acctNo + "'";
//                        ResultSet rs = statement.executeQuery(sql);
//                        while (rs.next()) {
//                            // Add 5 elements to the array list
//                            for (int i = 0; i < 10; i++) {
//                                array.add(rs.getString(i + 1));
//                            }
//                        }
//                        if (!array.isEmpty()) {
//                            txtSearchAcctNo1.setText(array.get(8).toString());
//                            txtCustomerName1.setText(array.get(1).toString());
//                            txtCustomerlastName2.setText(array.get(2).toString());
//                            txtCurrBal1.setText(array.get(9).toString());
//                        } else {
//                            JOptionPane.showMessageDialog(this, "Bank Information With Account Number " + txtSearchAcctNo.getText() + " Not Found!", "Banking System - Bank Not Found", JOptionPane.INFORMATION_MESSAGE);
//                        }
//                    }
//                } catch (HeadlessException | ClassNotFoundException | SQLException e) {
//                    JOptionPane.showMessageDialog(this, "Error! Can't Connect be to Database! Please Contact System Administrator.", "Banking System - Connection Error.", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        }catch(Exception e){
//           e.printStackTrace();
//        }
                //-----------------------------------------------------------------
//                ResultSet rs = null;
//                PreparedStatement ps = null;
//                try {
//                    Class.forName("com.mysql.cj.jdbc.Driver");
//                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "Vikram@123");
//                    String query = "select * from registration  where accountno=?";
//
//                    ps = con.prepareStatement(query);
//                    ps.setString(1, jTextField2.getText());
//                    rs = ps.executeQuery();
//                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//           if(rs.next()){
//               String add1 = rs.getString("Balance");
//               jTextField2.setText(add1);
//               rs.close();
//               ps.close();
//           }
//           else{
//               JOptionPane.showMessageDialog(null,"Enter correct Acc");
//           }
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, e);
//
//                } finally {
//                    try {
//                        rs.close();
//                        ps.close();
//
//                    } catch (Exception e) {
//
//                    }
//                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
             * @param args the command line arguments
             */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private static class txtCustomerlastName2 {

        private static void setText(String toString) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtCustomerlastName2() {
        }
    }

    private static class txtSearchAcctNo {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtSearchAcctNo() {
        }
    }
}
